# Generated by Django 3.0.4 on 2020-03-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news_paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_paper_name', models.CharField(max_length=50)),
                ('news_title', models.CharField(max_length=500)),
                ('news_link', models.CharField(max_length=500)),
                ('publication_time', models.DateTimeField()),
                ('data_fetching_time', models.DateTimeField()),
            ],
        ),
    ]
