# Generated by Django 3.0.4 on 2020-03-23 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0002_auto_20200322_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_paper',
            name='data_fetching_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 11, 20, 1, 234336)),
        ),
    ]
